name: Build and Push Helper Image

on:
  schedule:
    - cron: '0 0 * * *' # Daily
  push:
    branches:
      - 'master'
    paths:
      - 'Dockerfile'
      - '.github/workflows/build-helper.yml'
  pull_request:
    branches:
      - 'master'
    paths:
      - 'Dockerfile'
      - '.github/workflows/build-helper.yml'
  workflow_dispatch:

env:
  package_repo: ghcr.io/${{ github.repository_owner }}/dockertools-helper

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - id: get-time
        run: |
          tp=$(date -u +'%Y%m%d_%H%M%S')
          echo "::set-output name=build-time::$tp"
          echo Timestamp: $tp

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: check-if-base-image-updated
        if: ${{ github.event_name == 'schedule' }}
        name: check-if-base-image-updated
        uses: ./.github/actions/check-if-base-image-updated
        with:
          package-tag: ${{ env.package_repo }}:latest

      - id: check-if-os-upgradable
        if: ${{ github.event_name == 'schedule' && steps.check-if-base-image-updated.outputs.result == '0' }}
        name: check-if-os-upgradable
        uses: ./.github/actions/check-if-os-upgradable
        with:
          package-tag: ${{ env.package_repo }}:latest

      - run: |
          echo steps.check-if-base-image-updated.outputs.result = ${{ steps.check-if-base-image-updated.outputs.result }}
          echo steps.check-if-os-upgradable.outputs.result = ${{ steps.check-if-os-upgradable.outputs.result }}

      - name: Do build and push
        if: ${{ steps.check-if-base-image-updated.outcome == 'skipped' || steps.check-if-base-image-updated.outputs.result != '0' || steps.check-if-os-upgradable.outputs.result != '0' }}
        uses: ./.github/actions/build-and-push
        with:
            package-version: ${{ steps.get-time.outputs.build-time }}